name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Monday 9AM build
    - cron: '0 9 * * 1'

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Python dependencies
      run: |
        python -m pip install cookiecutter
    - name: Generate package
      run: |
        cookiecutter --no-input ./ -o ../test
    - name: Run default tox jobs
      run: |
        cd ../test/asdf-example-schemas
        tox
